parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: projetindus
    database_user: root
    database_password: nintendomanga
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true


    popular_parameter_days:  14
    popular_limit:     20
    artistes_return:   10

    sessions_return :  10
    ecoutes_return :   10

    note_tag : 0.10

    type_note_item : 0
    type_note_artist : 1
    type_note_tag : 2

    allowed_groups : 2


    api_key: Yzc0YmI1YzUtY2IzNi00NjY1LTgyMTQtMTUyZGQ1OTczMjFj
    api_secret: YTYyMTI0NTItYmNjMi00MTU0LTk3ZjItZTdhNDJlMDVkZDVm
    username_rhapsody: o-sayaka-o@hotmail.fr
    password_rhapsody: tabigi
    api_key_last: 30c3c9603ff7e5fba386bf8348abdb46
