_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

_assetic:
    resource: .
    type:     assetic

# Not present in packagist
#ProfilerLiveBundle:
#    resource: "@ProfilerLiveBundle/Resources/config/routing.yml"
#    prefix:   /