by_example_recommandations:
    resource: "@ByExampleRecommandationsBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /change-password

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /

byexample_demo_securityrest:
    resource: ByExample\DemoBundle\Controller\SecurityController
    type: rest

restroutes:
    resource: "@ByExampleDemoBundle/Resources/config/rest_routes.yml"
    type: rest

algoroutes:
    resource: "@ByExampleRecommandationsBundle/Resources/config/routing.yml"
    type: rest

#byexample_demo_rest:
#    resource: "@ByExampleDemoBundle/Resources/config/rest_routes.yml"
#    type: rest
#    prefix: /api
