<?php

namespace ByExample\DemoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PlaylistRestController__JMSInjector
{
    public static function inject($container) {
        $instance = new \ByExample\DemoBundle\Controller\PlaylistRestController();
        return $instance;
    }
}
