<?php

namespace ByExample\RecommandationsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RecommandationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \ByExample\RecommandationsBundle\Controller\RecommandationController();
        return $instance;
    }
}
