<?php

namespace Proxies\__CG__\ByExample\RecommandationsBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Recommandation extends \ByExample\RecommandationsBundle\Entity\Recommandation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function setIdalgorithm(\ByExample\RecommandationsBundle\Entity\Algorithm $idalgorithm = NULL)
    {
        $this->__load();
        return parent::setIdalgorithm($idalgorithm);
    }

    public function getIdalgorithme()
    {
        $this->__load();
        return parent::getIdalgorithme();
    }

    public function setIdutilisateur(\ByExample\DemoBundle\Entity\Utilisateur $idutilisateur = NULL)
    {
        $this->__load();
        return parent::setIdutilisateur($idutilisateur);
    }

    public function getIdutilisateur()
    {
        $this->__load();
        return parent::getIdutilisateur();
    }

    public function setIditem(\ByExample\DemoBundle\Entity\Item $iditem = NULL)
    {
        $this->__load();
        return parent::setIditem($iditem);
    }

    public function getIditem()
    {
        $this->__load();
        return parent::getIditem();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'date', 'idalgorithm', 'idutilisateur', 'iditem');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}