<?php

namespace Proxies\__CG__\ByExample\DemoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Session extends \ByExample\DemoBundle\Entity\Session implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDatedebut($datedebut)
    {
        $this->__load();
        return parent::setDatedebut($datedebut);
    }

    public function getDatedebut()
    {
        $this->__load();
        return parent::getDatedebut();
    }

    public function setDatefin($datefin)
    {
        $this->__load();
        return parent::setDatefin($datefin);
    }

    public function getDatefin()
    {
        $this->__load();
        return parent::getDatefin();
    }

    public function addIdecoute(\ByExample\DemoBundle\Entity\Ecoute $idecoute)
    {
        $this->__load();
        return parent::addIdecoute($idecoute);
    }

    public function removeIdecoute(\ByExample\DemoBundle\Entity\Ecoute $idecoute)
    {
        $this->__load();
        return parent::removeIdecoute($idecoute);
    }

    public function getIdecoute()
    {
        $this->__load();
        return parent::getIdecoute();
    }

    public function addIdplaylist(\ByExample\DemoBundle\Entity\Playlist $idplaylist)
    {
        $this->__load();
        return parent::addIdplaylist($idplaylist);
    }

    public function removeIdplaylist(\ByExample\DemoBundle\Entity\Playlist $idplaylist)
    {
        $this->__load();
        return parent::removeIdplaylist($idplaylist);
    }

    public function getIdplaylist()
    {
        $this->__load();
        return parent::getIdplaylist();
    }

    public function addIdtag(\ByExample\DemoBundle\Entity\Tag $idtag)
    {
        $this->__load();
        return parent::addIdtag($idtag);
    }

    public function removeIdtag(\ByExample\DemoBundle\Entity\Tag $idtag)
    {
        $this->__load();
        return parent::removeIdtag($idtag);
    }

    public function getIdtag()
    {
        $this->__load();
        return parent::getIdtag();
    }

    public function setIdutilisateur(\ByExample\DemoBundle\Entity\Utilisateur $idutilisateur = NULL)
    {
        $this->__load();
        return parent::setIdutilisateur($idutilisateur);
    }

    public function getIdutilisateur()
    {
        $this->__load();
        return parent::getIdutilisateur();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'datedebut', 'datefin', 'idecoute', 'idplaylist', 'idtag', 'idutilisateur');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}