<?php

namespace Proxies\__CG__\ByExample\DemoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Utilisateur extends \ByExample\DemoBundle\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setDateinscription($dateinscription)
    {
        $this->__load();
        return parent::setDateinscription($dateinscription);
    }

    public function getDateinscription()
    {
        $this->__load();
        return parent::getDateinscription();
    }

    public function setBirthdate($age)
    {
        $this->__load();
        return parent::setBirthdate($age);
    }

    public function getBirthdate()
    {
        $this->__load();
        return parent::getBirthdate();
    }

    public function setGenre($genre)
    {
        $this->__load();
        return parent::setGenre($genre);
    }

    public function getGenre()
    {
        $this->__load();
        return parent::getGenre();
    }

    public function setPays($pays)
    {
        $this->__load();
        return parent::setPays($pays);
    }

    public function getPays()
    {
        $this->__load();
        return parent::getPays();
    }

    public function addIdutilisateurami(\ByExample\DemoBundle\Entity\Utilisateur $idutilisateurami)
    {
        $this->__load();
        return parent::addIdutilisateurami($idutilisateurami);
    }

    public function removeIdutilisateurami(\ByExample\DemoBundle\Entity\Utilisateur $idutilisateurami)
    {
        $this->__load();
        return parent::removeIdutilisateurami($idutilisateurami);
    }

    public function getIdutilisateurami()
    {
        $this->__load();
        return parent::getIdutilisateurami();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'dateinscription', 'birthdate', 'genre', 'pays', 'idutilisateurami', 'idgroup', 'idordre');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}