<?php

namespace Proxies\__CG__\ByExample\DemoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Playlist extends \ByExample\DemoBundle\Entity\Playlist implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setDatecreation($datecreation)
    {
        $this->__load();
        return parent::setDatecreation($datecreation);
    }

    public function getDatecreation()
    {
        $this->__load();
        return parent::getDatecreation();
    }

    public function addIditem(\ByExample\DemoBundle\Entity\Item $iditem)
    {
        $this->__load();
        return parent::addIditem($iditem);
    }

    public function removeIditem(\ByExample\DemoBundle\Entity\Item $iditem)
    {
        $this->__load();
        return parent::removeIditem($iditem);
    }

    public function getIditem()
    {
        $this->__load();
        return parent::getIditem();
    }

    public function addIdsession(\ByExample\DemoBundle\Entity\Session $idsession)
    {
        $this->__load();
        return parent::addIdsession($idsession);
    }

    public function removeIdsession(\ByExample\DemoBundle\Entity\Session $idsession)
    {
        $this->__load();
        return parent::removeIdsession($idsession);
    }

    public function getIdsession()
    {
        $this->__load();
        return parent::getIdsession();
    }

    public function addIdtag(\ByExample\DemoBundle\Entity\Tag $idtag)
    {
        $this->__load();
        return parent::addIdtag($idtag);
    }

    public function removeIdtag(\ByExample\DemoBundle\Entity\Tag $idtag)
    {
        $this->__load();
        return parent::removeIdtag($idtag);
    }

    public function getIdtag()
    {
        $this->__load();
        return parent::getIdtag();
    }

    public function setIdutilisateur(\ByExample\DemoBundle\Entity\Utilisateur $idutilisateur = NULL)
    {
        $this->__load();
        return parent::setIdutilisateur($idutilisateur);
    }

    public function getIdutilisateur()
    {
        $this->__load();
        return parent::getIdutilisateur();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'datecreation', 'iditem', 'idsession', 'idtag', 'idutilisateur', 'idplaylistitem');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}