<?php

namespace ByExample\DemoBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\EntityRepository;
use ByExample\DemoBundle\Entity\Interactions;
use Doctrine\ORM\Query;
use \DateTime;

/**
 * InteractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractionRepository extends EntityRepository{

	public function addInteraction($typeInteraction, $ecoute){
		$interaction = new Interactions();
		$interaction->setDateheure(new DateTime());

		
		$interaction->setIdtypeinteraction($typeInteraction);
		$interaction->setIdecoute($ecoute);

		$this->_em->persist($interaction);
		$this->_em->flush();

		$idInteraction = $interaction->getId();

	    return $idInteraction;
	}
}